### ISSUE TITLE
Show Connections in Service Dependencies

### ISSUE THREAD

**Issue by majoraze** [AOEpeople/vistecture#12]
Hey there!

There are any planning on adding support on the 'serve' option to show connection dependencies in service level? There are only arrows in the dependencies on application level, and declaring in both generates shitty graphs with poluited and multiple arrows.

Thanks

**Comment by danielpoe** [comment]
Hey 

Thanks for Feedback - Can you explain what you mean I don't get it - sorry?

Cheers,

**Comment by majoraze** [comment]
Sorry for the poor feedback, I was in a hurry at the moment.

Let me give you more details, I have several applications on my project definition, and I'm putting all the dependencies inside the service definition and not the application definition, like this:

```
name: authentication-service
description: Auth Service
technology: node
team: plataform
properties:
  deployment: Serverless Framework
provided-services:
- name: auth
  type: api
  dependencies:
    - reference: bob.auth
      relationship: customer-supplier
- name: auth-customer
  type: api
  dependencies:
    - reference: alice-mobile-api.auth
- name: auth-logged
  type: publisher
  dependencies:
    - reference: authentication-service-events.auth-logged
      properties:
        event-type: SNS
- name: auth-customer-logged
  type: publisher
  dependencies:
    - reference: authentication-service-events.auth-customer-logged
      properties:
        event-type: SNS
infrastructure-dependencies:
  - type: DynamoDb
  - type: VPC
```

In the Graphviz It's showing the connections gracefully from the application services to the other application services, as this image shows:

https://imgur.com/VcFhAOy

But in the 'real time' visualization with the commando `vistecture serve`, its not linking the connections that come from the service dependencies and don't even show in the dependencies section, like the image shows:

https://imgur.com/MefA8g6
*the one that is showing connected is the only one I declared in the application level dependencies 

To illustrate what I'm trying to do, I was creating a microservice ecosystem with event-driven architecture and I also want to document the pub/sub events, that's why I have the `authentication-service-events` application, so I can know which service publishes the event and which one is subscribing. I can duplicate the definition on the application level and service level to show in the `serve` all the connections correctly but in the `analyse` command It will show circular dependency and in the graphviz it will duplicate the arrows leaving the service definition, resulting in a shitty graph (that was what I was trying to say in the first post).

I believe that defining the dependencies in the service level will also need have to link the connections in the `serve` command and also not count as circular dependency in the application level as it is the service inside that application that is connected to another (and the services inside an application could be decoupled in another microservices, like lambdas, and the application is just a form to group them) so at least in the case of circular dependency inside a service maybe a warning will be enough.

Let me know if you need more details. 

And congrats! Awesome tool, I was trying for days to find some that is simple and document right all this ecosystem but without over document, because the system documentation is in his own repository. I'm just trying to show all the ecosystem of the applications of the company, and how they connect to each other.

Thanks!
